# Generated by Django 5.2.8 on 2025-11-23 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0001_initial'),
        ('supliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflows',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='products.product'),
        ),
        migrations.AddField(
            model_name='inflows',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='supliers.suplier'),
        ),
    ]
